---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
library(tidyverse)
library(readr)
dane_nieruchomosci <- read_csv("dane_nieruchomosci/apartments_pl_2024_06.csv")
```

# Wstęp

Rynek nieruchomości jest jednym z najważniejszych sektorów polskiej
gospodarki, decyduje o możliwościach zakupu mieszkania przez Polaków,
atrakcyjności inwestycji oraz kondycji całej branży budowlanej. W 2024
roku, dzięki stabilizacji stóp procentowych, rosnącym płacom i niskiej
inflacji, zdolność kredytowa gospodarstw domowych wyraźnie się
poprawiła. Niniejszy projekt koncentruje się wyłącznie na danych z
czerwca 2024 roku, dzięki czemu pozwala dokładnie uchwycić aktualny
poziom cen tuż po okresie dynamicznych wzrostów z poprzednich miesięcy.

## Pytania badawcze

1.  Jak kształtują się średnie ceny mieszkań w 15 największych miastach
    Polski?
2.  Które miasta charakteryzują się najwyższymi, a które najniższymi
    cenami za metr kwadratowy?
3.  W jaki sposób powierzchnia mieszkania wpływa na jego cenę całkowitą
    oraz cenę za metr kwadratowy?
4.  Jak odległość od centrum miasta wpływa na poziom cen mieszkań?
5.  W jaki sposób stan techniczny mieszkania przekłada się na jego
    wartość rynkową?
6.  Jakie znaczenie mają udogodnienia, takie jak balkon, winda czy
    miejsce parkingowe, dla poziomu ceny ofertowej?
7.  Jak typ budynku wpływa na poziom cen?
8.  Jakie są różnice w cenach mieszkań w zależności od liczby pokoi?

# Opis danych

Zbiór danych zawiera miesięczną kolekcję ofert sprzedaży z czerwca 2024
roku z 15 największych polskich miast.

Zbiór danych zawiera `r nrow("apartments_pl_2024_06.csv")` obserwacji i
`r ncol("apartments_pl_2024_06.csv")` zmiennych.

Poniżej znajduje się opis najważniejszych zmiennych:

-   `city`: Nazwa miasta, w którym znajduje się nieruchomość,

-   `type`: Typ budynku,

-   `squareMeters`: Wielkość mieszkania w metrach kwadratowych,

-   `rooms`: Liczba pokoi w mieszkaniu,

-   `buildYear`: Rok, w którym budynek został zbudowany,

-   `centreDistance`: Odległość od centrum miasta w kilometrach,

-   `poiCount`: Liczba interesujących miejsc (POI) w promieniu 500m,

-   `[poiName]Distance`: Odległość do najbliższego konkretnego punktu
    POI,

-   `własność`: Rodzaj własności nieruchomości,

-   `condition`: Stan mieszkania,

-   `has[features]`: Zmienne binarne określające kluczowe udogodnienia,

-   `cena`: Cena ofertowa sprzedaży w złotych polskich.
